# Assumptions : aLL database methods will be called holding a global lock
import psycopg

from agentpit.datastructures.market_state import MarketState


class TableCreate:
    @staticmethod
    def create_trades_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS trades (
                TRADE_ID TEXT PRIMARY KEY,
                TAKER_ORDER_ID TEXT,
                MAKER_ORDERS TEXT,
                MARKET TEXT,
                ASSET_ID TEXT,
                PRICE BIGINT,
                TRADE_SIZE BIGINT,
                REMAINING_SIZE BIGINT,
                SIDE TEXT,
                STATUS TEXT,
                MATCH_TIME BIGINT,
                TRANSACTION_HASH TEXT,
                BUCKET_INDEX INTEGER,
                FEE_RATE_BPS BIGINT,
                TAKER_API_KEY TEXT,
                MAKER_API_KEY TEXT
            )
            """
        )

    @staticmethod
    def create_orders_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS orders (
                API_KEY TEXT,
                PRICE BIGINT,
                POST_ONLY INTEGER,
                ORDER_TYPE TEXT,
                SALT TEXT,
                MAKER TEXT,
                TAKER TEXT,
                SIGNER TEXT,
                TOKEN_ID TEXT,
                MAKER_AMOUNT BIGINT,
                TAKER_AMOUNT BIGINT,
                EXPIRATION BIGINT,
                NONCE INTEGER,
                FEE_RATE_BPS BIGINT,
                SIDE TEXT,
                SIGNATURE_TYPE INTEGER,
                SIGNATURE TEXT,
                ORDER_JSON TEXT,
                STATUS TEXT DEFAULT 'live',
                REMAINING_AMOUNT BIGINT,
                CREATED_AT BIGINT,
                ORDER_ID TEXT PRIMARY KEY
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_orders_price_side ON orders(PRICE, SIDE)"
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_orders_order_type_status_expiration
                ON orders(ORDER_TYPE, STATUS, EXPIRATION)
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_orders_status_expiration
                ON orders(STATUS, EXPIRATION)
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_orders_api_key ON orders(API_KEY)")

    @staticmethod
    def create_users_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                USER_ID         TEXT PRIMARY KEY,
                EMAIL           TEXT NOT NULL UNIQUE,
                PASSWORD_HASH   TEXT NOT NULL,
                HANDLE          TEXT UNIQUE,
                ETH_ADDRESS     TEXT NOT NULL UNIQUE,
                ETH_PRIVATE_KEY TEXT NOT NULL UNIQUE,
                API_KEY         TEXT NOT NULL UNIQUE,
                ONBOARDED_AT    BIGINT,
                CREATED_AT      BIGINT NOT NULL,
                IS_BOT          INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(EMAIL)")
        TableCreate._migrate_users_table(conn)

    @staticmethod
    def _migrate_users_table(conn: psycopg.Connection) -> None:
        """Idempotent additive migration for the users table.

        Pre-auth versions of the schema only had USER_ID, API_KEY, ETH_PRIVATE_KEY.
        Add the new columns if they're missing so existing dev DBs keep working.
        """
        additions = [
            ("EMAIL", "TEXT"),
            ("PASSWORD_HASH", "TEXT"),
            ("HANDLE", "TEXT"),
            ("ETH_ADDRESS", "TEXT"),
            ("ONBOARDED_AT", "BIGINT"),
            ("CREATED_AT", "BIGINT"),
            ("IS_BOT", "INTEGER NOT NULL DEFAULT 0"),
        ]
        for col, col_type in additions:
            conn.execute(
                f"ALTER TABLE users ADD COLUMN IF NOT EXISTS {col} {col_type}"
            )

    @staticmethod
    def create_markets_table(conn: psycopg.Connection) -> None:
        allowed_states = ", ".join(f"'{s.value}'" for s in MarketState)
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS markets (
                MARKET_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                CONDITION_ID TEXT NOT NULL UNIQUE,
                POLYMARKET_ID BIGINT,
                POLYMARKET_CONDITION_ID TEXT,
                EVENT_ID BIGINT,
                OUTCOME_LABEL TEXT,
                ICON_URL TEXT,
                POLYMARKET_YES_TOKEN_ID TEXT,
                POLYMARKET_NO_TOKEN_ID TEXT,
                QUESTION TEXT NOT NULL,
                SLUG TEXT NOT NULL,
                DESCRIPTION TEXT NOT NULL,
                ERC1155_TOKENS TEXT NOT NULL,
                START_DATE BIGINT NOT NULL,
                END_DATE BIGINT,
                RESOLVED_OUTCOME INTEGER,
                MARKET_STATE TEXT NOT NULL DEFAULT '{MarketState.DRAFT.value}'
                    CHECK (MARKET_STATE IN ({allowed_states}))
            )
            """
        )
        conn.execute(
            "ALTER TABLE markets ADD COLUMN IF NOT EXISTS POLYMARKET_CONDITION_ID TEXT"
        )
        conn.execute(
            "ALTER TABLE markets ADD COLUMN IF NOT EXISTS EVENT_ID BIGINT"
        )
        conn.execute(
            "ALTER TABLE markets ADD COLUMN IF NOT EXISTS OUTCOME_LABEL TEXT"
        )
        conn.execute(
            "ALTER TABLE markets ADD COLUMN IF NOT EXISTS ICON_URL TEXT"
        )
        conn.execute(
            "ALTER TABLE markets ADD COLUMN IF NOT EXISTS POLYMARKET_YES_TOKEN_ID TEXT"
        )
        conn.execute(
            "ALTER TABLE markets ADD COLUMN IF NOT EXISTS POLYMARKET_NO_TOKEN_ID TEXT"
        )
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_markets_condition_id ON markets(CONDITION_ID)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_markets_polymarket_condition_id "
            "ON markets(POLYMARKET_CONDITION_ID)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_markets_event_id ON markets(EVENT_ID)"
        )

    @staticmethod
    def create_events_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS events (
                EVENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                SLUG TEXT NOT NULL UNIQUE,
                TITLE TEXT NOT NULL,
                DESCRIPTION TEXT NOT NULL DEFAULT '',
                ICON_URL TEXT,
                CATEGORY TEXT,
                START_DATE BIGINT,
                END_DATE BIGINT,
                POLYMARKET_EVENT_ID TEXT
            )
            """
        )
        conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_events_slug ON events(SLUG)")
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_events_polymarket_event_id "
            "ON events(POLYMARKET_EVENT_ID)"
        )

    @staticmethod
    def create_transactions_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS transactions (
                TRANSACTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TIMESTAMP timestamptz DEFAULT now(),
                API_KEY TEXT NOT NULL,
                TRANSACTION_TYPE TEXT NOT NULL,
                MARKET_ID BIGINT,
                DETAILS TEXT
            )
            """
        )

    @staticmethod
    def create_agents_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS agents (
                AGENT_ID TEXT PRIMARY KEY,
                PERSONALITY TEXT NOT NULL,
                STATE TEXT NOT NULL DEFAULT '{}',
                HISTORY TEXT NOT NULL DEFAULT '[]',
                TODO TEXT NOT NULL DEFAULT '[]'
            )
            """
        )

    @staticmethod
    def create_personalities_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS personalities (
                PERSONALITY_ID TEXT PRIMARY KEY,
                PERSONALITY_TITLE TEXT NOT NULL,
                PERSONALITY_SPEC TEXT NOT NULL
            )
            """
        )

    @staticmethod
    def create_price_snapshots_table(conn: psycopg.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS price_snapshots (
                SNAPSHOT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                MARKET_ID BIGINT NOT NULL,
                ASSET_ID TEXT NOT NULL,
                T BIGINT NOT NULL,
                MID_MICRO_USD BIGINT NOT NULL
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_snapshots_market_t "
            "ON price_snapshots(MARKET_ID, T)"
        )

    @staticmethod
    def create_all_tables(conn: psycopg.Connection) -> None:
        # errors propagate; no exception handling here
        TableCreate.create_orders_table(conn)
        TableCreate.create_trades_table(conn)
        TableCreate.create_users_table(conn)
        TableCreate.create_agents_table(conn)
        TableCreate.create_personalities_table(conn)
        TableCreate.create_events_table(conn)
        TableCreate.create_markets_table(conn)
        TableCreate.create_transactions_table(conn)
        TableCreate.create_price_snapshots_table(conn)
